var coin_lang = ["请输入ID","请输入密码.",
	"请输入ID. (5-16 characters).",
	"请确认ID是否重复!",
	"推荐人ID.",
	"请输入密码.",
	"输入密码不一致!",
	"请输入姓名.",
	"是否储存现在信息?",
	"There are two or more sponsors",
	"Please enter the amount.",
	"Enter the amount to the number.",
	"The amount must be at least 100 $.",
	"Applications must specify the amount to 100 units.",
	"This amount is larger than E-Wallet balance.",
	"Please check the balance E-Wallet.",
	"Please enter your membership number of the person you want to send a gift.",
	"Do you want to save the current contents?",
	"Cash conversion",
	"Gift giving",
	"请确认密码.",
	"Please enter your mobile number.",
	"The password is changed.",
	"Do you want to change your ID?",
	"Please enter your Placement",
	"Please enter your name.",
	"Please choose again Amount.",
	"请选择套餐.",
	"It is greater than the retention E-Wallet",
	"Wallet and payments that are not the same.",
	"Please enter the deposit bitcoin address.",
	"Please enter your verification.",
	"无数据",
	"Applications must specify the amount to 900 units.",
	"It is greater than the retention Point",
	"The amount must be at least 500 coin",
	"The amount must be at least 3000 coin",
	"This amount is larger than LXZ Coin balance.\r\n\nPlease check the balance LXZ Coin.",
	"Please enter your Send Wallet Address"
];
