var coin_lang = ["Please enter the ID.","Please enter your password.",
	"Please enter the ID. (5-16 characters).",
	"Please check the ID duplication!",
	"Please enter your recommenders.",
	"Please enter your password.",
	"The two passwords do not match!",
	"Please enter your name.",
	"Do you want to save the current contents?",
	"There are two or more sponsors",
	"Please enter the amount.",
	"Enter the amount to the number.",
	"The amount must be at least 100 $.",
	"Applications must specify the amount to 100 units.",
	"This amount is larger than E-Wallet balance.",
	"Please check the balance E-Wallet.",
	"Please enter your membership number of the person you want to send a gift.",
	"Do you want to save the current contents?",
	"Cash conversion",
	"Gift giving",
	"Please confirm your password.",
	"Please enter your mobile number.",
	"The password is changed.",
	"Do you want to change your ID?",
	"Please enter your Placement",
	"Please enter your name.",
	"Please choose again Amount.",
	"Please select a product.",
	"It is greater than the retention E-Wallet",
	"Wallet and payments that are not the same.",
	"Please enter the deposit bitcoin address.",
	"Please enter your verification.",
	"No Data.",
	"Applications must specify the amount to 900 units.",
	"It is greater than the retention Point",
	"The amount must be at least 500 coin",
	"The amount must be at least 3000 coin",
	"This amount is larger than LXZ Coin balance.\r\n\nPlease check the balance LXZ Coin.",
	"Please enter your Send Wallet Address"
];
